- platform: mqtt
  name: Christian Loft
  command_topic: "cmnd/sonoff/christian/light/loft/POWER"
  state_topic: "stat/sonoff/christian/light/loft/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  brightness_command_topic: "cmnd/sonoff/christian/light/loft/DIMMER"
  brightness_scale: 100
  brightness_state_topic: "stat/sonoff/christian/light/loft/RESULT"
  brightness_value_template: "{{ value_json.Dimmer }}"
  rgb_command_topic: "cmnd/sonoff/christian/light/loft/COLOR"
  rgb_command_template: "{{ '%02x%02x%02x0000' | format(red, green, blue) }}"
  rgb_state_topic: "stat/sonoff/christian/light/loft/RESULT"
  rgb_value_template: "{{ value_json.Color[0:2]|int(base=16) }},{{ value_json.Color[2:4]|int(base=16) }},{{ value_json.Color[4:6]|int(base=16) }}"
  color_temp_command_topic: "cmnd/sonoff/christian/light/loft/CT"
  color_temp_state_topic: "cmnd/sonoff/christian/light/loft/RESULT"
  color_temp_value_template: "{{ value_json.CT }}"
  effect_command_topic: "cmnd/sonoff/christian/light/loft/SCHEME"
  effect_state_topic: "stat/sonoff/christian/light/loft/RESULT"
  effect_value_template: "{{ value_json.Scheme }}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  availability_topic: "tele/sonoff/christian/light/loft/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1