- platform: mqtt
  name: Bedroom Light 1
  command_topic: "cmnd/sonoff/bedroom/light/1/POWER"
  state_topic: "stat/sonoff/bedroom/light/1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  brightness_command_topic: "cmnd/sonoff/bedroom/light/1/DIMMER"
  brightness_scale: 100
  brightness_state_topic: "stat/sonoff/bedroom/light/1/RESULT"
  brightness_value_template: "{{ value_json.Dimmer | int }}"
  rgb_command_topic: "cmnd/sonoff/bedroom/light/1/COLOR"
  rgb_command_template: "{{ '%02x%02x%02x0000' | format(red, green, blue) }}"
  rgb_state_topic: "stat/sonoff/bedroom/light/1/RESULT"
  rgb_value_template: "{{ value_json.Color[0:2]|int(base=16) }},{{ value_json.Color[2:4]|int(base=16) }},{{ value_json.Color[4:6]|int(base=16) }}"
  color_temp_command_topic: "cmnd/sonoff/bedroom/light/1/CT"
  color_temp_state_topic: "cmnd/sonoff/bedroom/light/1/RESULT"
  color_temp_value_template: "{{ value_json.CT }}"
  effect_command_topic: "cmnd/sonoff/bedroom/light/1/SCHEME"
  effect_state_topic: "stat/sonoff/bedroom/light/1/RESULT"
  effect_value_template: "{{ value_json.Scheme }}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  availability_topic: "tele/sonoff/bedroom/light/1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
  
- platform: mqtt
  name: Bedroom Light 2
  command_topic: "cmnd/sonoff/bedroom/light/2/POWER"
  state_topic: "stat/sonoff/bedroom/light/2/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  brightness_command_topic: "cmnd/sonoff/bedroom/light/2/DIMMER"
  brightness_scale: 100
  brightness_state_topic: "stat/sonoff/bedroom/light/2/RESULT"
  brightness_value_template: "{{ value_json.Dimmer | int }}"
  rgb_command_topic: "cmnd/sonoff/bedroom/light/2/COLOR"
  rgb_command_template: "{{ '%02x%02x%02x0000' | format(red, green, blue) }}"
  rgb_state_topic: "stat/sonoff/bedroom/light/2/RESULT"
  rgb_value_template: "{{ value_json.Color[0:2]|int(base=16) }},{{ value_json.Color[2:4]|int(base=16) }},{{ value_json.Color[4:6]|int(base=16) }}"
  color_temp_command_topic: "cmnd/sonoff/bedroom/light/2/CT"
  color_temp_state_topic: "cmnd/sonoff/bedroom/light/2/RESULT"
  color_temp_value_template: "{{ value_json.CT }}"
  effect_command_topic: "cmnd/sonoff/bedroom/light/2/SCHEME"
  effect_state_topic: "stat/sonoff/bedroom/light/2/RESULT"
  effect_value_template: "{{ value_json.Scheme }}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  availability_topic: "tele/sonoff/bedroom/light/2/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  qos: 1
  
- platform: group
  name: bedroom_group
  entities:
    - light.bedroom_light_1
    - light.bedroom_light_2
  