- platform: mqtt
  name: Couch
  command_topic: "cmnd/sonoff/livingroom/light/couch/POWER"
  state_topic: "stat/sonoff/livingroom/light/couch/POWER"
  availability_topic: "tele/sonoff/livingroom/light/couch/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
# - platform: group
#   name: livingroom_group
#   entities:
#     - light.couch
#     - light.sofabord
