- platform: mqtt
  name: Kitchen
  command_topic: "cmnd/sonoff/kitchen/light/ceiling/POWER"
  state_topic: "stat/sonoff/kitchen/light/ceiling/POWER1"
  availability_topic: "tele/sonoff/kitchen/light/ceiling/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false