- platform: mqtt
  name: diningroom cupboard
  command_topic: "cmnd/sonoff/diningroom/light/cupboard/POWER"
  state_topic: "stat/sonoff/diningroom/light/cupboard/POWER"
  availability_topic: "tele/sonoff/diningroom/light/cupboard/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
