- id: '1581973993160'
  alias: Set Deconz config on startup
  description: ''
  trigger:
  - entity_id: sensor.deconz_container_state
    for:
      seconds: 10
    platform: state
    to: running
  condition: []
  action:
  - data:
      data:
        config:
          duration: 10
      entity: binary_sensor.motion_bathroom
    service: deconz.configure
