homeassistant:
  name: Horsensvej
  latitude: !secret loc_latitude
  longitude: !secret loc_longitude
  elevation: 62
  unit_system: metric
  time_zone: Europe/Copenhagen
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /tmp

frontend:
  extra_html_url:
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui.html
  themes: !include_dir_merge_named themes

config:

http:
  base_url: !secret baseurl

updater:

discovery:

history:

logbook:

map:

sun:

person:

wake_on_lan:

system_health:

mobile_app:

shelly:
  discovery: true  #add all devices (default)
  sensors:
    - all #show all sensors
  devices:  #configure devices
    - id: "7650cb"
      name: Bryggers Flood #set friendly name

google:
  client_id: !secret google_calendar_id
  client_secret: !secret google_calendar_secret

# Include
#########
alarm_control_panel: !include resources/bwalarm/bwalarm.yaml
camera: !include include_conf/conf_camera.yaml
cloud: !include include_conf/conf_cloud.yaml
device_tracker: !include include_conf/conf_device_tracker.yaml
garbage_collection: !include include_conf/conf_garbage.yaml
hue: !include include_conf/conf_hue.yaml
influxdb: !include include_conf/conf_influxdb.yaml
modbus: !include include_conf/conf_modbus.yaml
netatmo: !include include_conf/conf_netatmo.yaml
notify: !include include_conf/conf_notify.yaml
panel_custom: !include include_conf/conf_panel_custom.yaml
panel_iframe: !include include_conf/conf_panel_iframe.yaml
proximity: !include include_conf/conf_proximity.yaml
recorder: !include include_conf/conf_recorder.yaml
repetier: !include include_conf/conf_repetier.yaml
scene: !include scenes.yaml
tts: !include include_conf/conf_tts.yaml
twilio: !include include_conf/conf_twilio.yaml
unifi: !include include_conf/conf_unifi.yaml
vera: !include include_conf/conf_vera.yaml
automation: !include automations.yaml

# Include_list
##############
binary_sensor: !include_dir_merge_list include_binary/
cover: !include_dir_merge_list include_cover/
display: !include_dir_merge_list include_display/
light: !include_dir_merge_list include_lights/
media_player: !include_dir_merge_list include_media_player/
sensor: !include_dir_merge_list include_sensors/
switch: !include_dir_merge_list include_switch/
vacuum: !include_dir_merge_list include_vacuum/

# Include_named
###############
input_boolean: !include_dir_merge_named include_booleans/
input_number: !include_dir_merge_named include_numbers/
input_select: !include_dir_merge_named include_input_select/
script: !include_dir_merge_named include_scripts/
utility_meter: !include_dir_merge_named include_utility_meter/

#landroid_cloud:
#  email: !secret landroid_email
#  password: !secret landroid_pass

#logger:
#  default: warning
#  logs:
#    # log level for HA core
#    homeassistant.core: warning
#    homeassistant.components.cloud.google_config: debug