homeassistant:
  name: Horsensvej
  latitude: !secret loc_latitude
  longitude: !secret loc_longitude
  elevation: 62
  unit_system: metric
  time_zone: Europe/Copenhagen
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /tmp
    - /config/www/deepstack

frontend:
  extra_html_url:
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui.html
  themes: !include_dir_merge_named themes
  #themes: !include_dir_merge_named include_themes/

config:

http:
  base_url: !secret baseurl

updater:

discovery:

history:

logbook:

map:

sun:

person:

wake_on_lan:

system_health:

mobile_app:

# Include
#########
alarm_control_panel: !include resources/bwalarm/bwalarm.yaml
vera: !include include_conf/conf_vera.yaml
hue: !include include_conf/conf_hue.yaml
#mysensors: !include include_conf/conf_mysensors.yaml
panel_custom: !include include_conf/conf_panel_custom.yaml
panel_iframe: !include include_conf/conf_panel_iframe.yaml
notify: !include include_conf/conf_notify.yaml
influxdb: !include include_conf/conf_influxdb.yaml
device_tracker: !include include_conf/conf_device_tracker.yaml
tts: !include include_conf/conf_tts.yaml
recorder: !include include_conf/conf_recorder.yaml
cloud: !include include_conf/conf_cloud.yaml
#zoneminder: !include include_conf/conf_zoneminder.yaml
camera: !include include_conf/conf_camera.yaml
image_processing: !include include_conf/conf_imageprocessing.yaml
netatmo: !include include_conf/conf_netatmo.yaml
twilio: !include include_conf/conf_twilio.yaml
repetier: !include include_conf/conf_repetier.yaml
modbus: !include include_conf/conf_modbus.yaml
unifi: !include include_conf/conf_unifi.yaml
proximity: !include include_conf/conf_proximity.yaml
mbweather: !include include_conf/conf_mbweather.yaml
garbage_collection: !include include_conf/conf_garbage.yaml
scene: !include scenes.yaml

# Include_list
##############
automation: !include_dir_merge_list include_automations/
light: !include_dir_merge_list include_lights/
sensor: !include_dir_merge_list include_sensors/
zone: !include_dir_merge_list include_zones/
binary_sensor: !include_dir_merge_list include_binary/
cover: !include_dir_merge_list include_cover/
switch: !include_dir_merge_list include_switch/
media_player: !include_dir_merge_list include_media_player/
vacuum: !include_dir_merge_list include_vacuum/
display: !include_dir_merge_list include_display/

# Include_named
###############
input_select: !include_dir_merge_named include_input_select/
group: !include_dir_merge_named include_groups/
script: !include_dir_merge_named include_scripts/
input_boolean: !include_dir_merge_named include_booleans/
input_number: !include_dir_merge_named include_numbers/
# input_datetime: !include_dir_merge_named include_datetime/

#landroid_cloud:
#  email: !secret landroid_email
#  password: !secret landroid_pass

#logger:
#  default: warning
#  logs:
#    # log level for HA core
#    homeassistant.core: warning
#    homeassistant.components.cloud.google_config: debug

