homeassistant:
  name: Home
  latitude: !secret loc_latitude
  longitude: !secret loc_longitude
  elevation: 62
  unit_system: metric
  time_zone: Europe/Copenhagen
  customize: !include_dir_merge_named include_customize/
  customize_glob: !include customize_glob.yaml

frontend:
  themes: !include_dir_merge_named include_themes/
  extra_html_url:
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui.html
    - /local/custom-ui/custom-weather-card.html
  extra_html_url_es5:
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui-es5.html
    - /local/custom-ui/custom-weather-card.html

config:

http:
  base_url: !secret baseurl

updater:

discovery:

history:

logbook:

map:

sun:

person:

system_health:

vera: !include include_conf/conf_vera.yaml
hue: !include include_conf/conf_hue.yaml
mysensors: !include include_conf/conf_mysensors.yaml
panel_iframe: !include include_conf/conf_panel_iframe.yaml
notify: !include include_conf/conf_notify.yaml
influxdb: !include include_conf/conf_influxdb.yaml
device_tracker: !include include_conf/conf_device_tracker.yaml
tts: !include include_conf/conf_tts.yaml
recorder: !include include_conf/conf_recorder.yaml
cloud: !include include_conf/conf_cloud.yaml
zoneminder: !include include_conf/conf_zoneminder.yaml
camera: !include include_conf/conf_camera.yaml
image_processing: !include include_conf/conf_imageprocessing.yaml
googlehome: !include include_conf/conf_google_home.yaml


group: !include_dir_merge_named include_groups/
automation: !include_dir_merge_list include_automations/
script: !include_dir_merge_named include_scripts/
light: !include_dir_merge_list include_lights/
input_boolean: !include_dir_merge_named include_booleans/
input_number: !include_dir_merge_named include_numbers/
input_datetime: !include_dir_merge_named include_datetime/
sensor: !include_dir_merge_list include_sensors/
zone: !include_dir_merge_list include_zones/
binary_sensor: !include_dir_merge_list include_binary/
cover: !include_dir_merge_list include_cover/
switch: !include_dir_merge_list include_switch/
media_player: !include_dir_merge_list include_media_player/
#input_text: !include_dir_merge_named include_text/
#calendar: !include_dir_merge_list include_calendar/
