- platform: broadlink
  host: 192.168.1.220
  mac: '78:0F:77:51:A3:E8'
  timeout: 15
  # switches:
  #   # Will work on most Phillips TVs:
  #   tv_philips:
  #     friendly_name: "Philips Tv Power"
  #     command_on: 'JgA0AVceDx0PDw0QDR8fDw0QDhAODw4PDw8NEA8PDRAOEA0QDRAdEA4eDg8OAArPVx4OHg4PDhAOHh4QDRAODw8PDRAOEA0QDRAOEA0QDw8ODxwQDh4PDw0ACtBXHg4eDg8OEA0fHhANEA4PDw8NEA4QDRAODw8PDRAPDw0QHQ8OHg8PDQAKz1cfDh4ODw0QDx0fDw8PDg8ODw4QDg8OEA0QDhANEA4PDw8cEA4eDg8PAArOVx4PHQ8PDRAOHh4QDhANEA4PDw8NEA4QDRANEA8PDRAOEBwQDh4ODw4ACs9XHg4eDg8OEA0fHw8NEA4QDg8NEA4QDRAOEA0QDg8OEA0QHRANHw4PDQAKz1ceDx0PDw0QDh4fDw4PDhANEA8PDRAODw4QDRAOEA0QDhAcEA4eDg8OAA0FAAAAAA=='
  #     command_off: 'JgA0AVceDx0PDw0QDR8fDw0QDhAODw4PDw8NEA8PDRAOEA0QDRAdEA4eDg8OAArPVx4OHg4PDhAOHh4QDRAODw8PDRAOEA0QDRAOEA0QDw8ODxwQDh4PDw0ACtBXHg4eDg8OEA0fHhANEA4PDw8NEA4QDRAODw8PDRAPDw0QHQ8OHg8PDQAKz1cfDh4ODw0QDx0fDw8PDg8ODw4QDg8OEA0QDhANEA4PDw8cEA4eDg8PAArOVx4PHQ8PDRAOHh4QDhANEA4PDw8NEA4QDRANEA8PDRAOEBwQDh4ODw4ACs9XHg4eDg8OEA0fHw8NEA4QDg8NEA4QDRAOEA0QDg8OEA0QHRANHw4PDQAKz1ceDx0PDw0QDh4fDw4PDhANEA8PDRAODw4QDRAOEA0QDhAcEA4eDg8OAA0FAAAAAA=='