- platform: template
  switches:
    livingroom_tv:
      friendly_name: Philips TV
      value_template: "{{ is_state('binary_sensor.stue_tv', 'on') }}"
      turn_on:
        # service: script.turn_on
        # data:
        #   entity_id: script.toggle_livingroom_tv_power
        service: switch.broadlink_send_packet_192_168_1_220
        data:
          packet:
            - "JgA0AVceDx0PDw0QDR8fDw0QDhAODw4PDw8NEA8PDRAOEA0QDRAdEA4eDg8OAArPVx4OHg4PDhAOHh4QDRAODw8PDRAOEA0QDRAOEA0QDw8ODxwQDh4PDw0ACtBXHg4eDg8OEA0fHhANEA4PDw8NEA4QDRAODw8PDRAPDw0QHQ8OHg8PDQAKz1cfDh4ODw0QDx0fDw8PDg8ODw4QDg8OEA0QDhANEA4PDw8cEA4eDg8PAArOVx4PHQ8PDRAOHh4QDhANEA4PDw8NEA4QDRANEA8PDRAOEBwQDh4ODw4ACs9XHg4eDg8OEA0fHw8NEA4QDg8NEA4QDRAOEA0QDg8OEA0QHRANHw4PDQAKz1ceDx0PDw0QDh4fDw4PDhANEA8PDRAODw4QDRAOEA0QDhAcEA4eDg8OAA0FAAAAAA=="
      turn_off:
        # service: script.turn_on
        # data:
        #   entity_id: script.toggle_livingroom_tv_power
        service: switch.broadlink_send_packet_192_168_1_220
        data:
          packet:
            - "JgA0AVceDx0PDw0QDR8fDw0QDhAODw4PDw8NEA8PDRAOEA0QDRAdEA4eDg8OAArPVx4OHg4PDhAOHh4QDRAODw8PDRAOEA0QDRAOEA0QDw8ODxwQDh4PDw0ACtBXHg4eDg8OEA0fHhANEA4PDw8NEA4QDRAODw8PDRAPDw0QHQ8OHg8PDQAKz1cfDh4ODw0QDx0fDw8PDg8ODw4QDg8OEA0QDhANEA4PDw8cEA4eDg8PAArOVx4PHQ8PDRAOHh4QDhANEA4PDw8NEA4QDRANEA8PDRAOEBwQDh4ODw4ACs9XHg4eDg8OEA0fHw8NEA4QDg8NEA4QDRAOEA0QDg8OEA0QHRANHw4PDQAKz1ceDx0PDw0QDh4fDw4PDhANEA8PDRAODw4QDRAOEA0QDhAcEA4eDg8OAA0FAAAAAA=="
