- platform: unifi
  host: !secret unifi_host
  username: !secret unifi_user
  password: !secret unifi_pass
  verify_ssl: false
  consider_home: 300
  interval_seconds: 10
  track_new_devices: false
  ssid_filter:
    - 'Trab.dk'
    - 'Christian'
    - 'Michael'
