- platform: template
  sensors:
    battery_heat_repos:
      friendly_name: "Repos"
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.climate.repos_13 -%}
          {{ states.climate.repos_13.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
    battery_heat_michael:
      friendly_name: "Michael"
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.climate.michael_14 -%}
          {{ states.climate.michael_14.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
    battery_heat_christian:
      friendly_name: "Christian"
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.climate.christian_12 -%}
          {{ states.climate.christian_12.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
    battery_heat_trainroom:
      friendly_name: "Togrum"
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.climate.disponibel_11 -%}
          {{ states.climate.disponibel_11.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}

    battery_heat_livingroom:
      friendly_name: "Stue"
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.climate.netatmo_stue -%}
          {{ states.climate.netatmo_stue.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}

    battery_heat_kitchen:
      friendly_name: "Køkken"
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.climate.netatmo_kokken -%}
          {{ states.climate.netatmo_kokken.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
