- platform: tcp
  name: meteobridge_out_temp
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charset=UTF-8\n\n"   
  value_template: "{{value.split (' ')[2]}}"
  unit_of_measurement: °C

- platform: tcp
  name: meteobridge_out_humidity
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charset=UTF-8\n\n"
  value_template: "{{value.split (' ')[3]}}"
  unit_of_measurement: '%'

- platform: tcp
  name: meteobridge_out_dewpoint
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charset=UTF-8\n\n"
  value_template: "{{value.split (' ')[4] }}"
  unit_of_measurement: °C

- platform: tcp
  name: meteobridge_wind_direction
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charset=UTF-8\n\n"
  value_template: "{{value.split (' ')[20]}}"
  unit_of_measurement: °

- platform: tcp
  name: meteobridge_wind_gust
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charset=UTF-8\n\n"
  value_template: "{{value.split (' ')[21]}}"
  unit_of_measurement: m/s

- platform: tcp
  name: meteobridge_wind_speed
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charset=UTF-8\n\n"
  value_template: "{{value.split (' ')[22]}}"
  unit_of_measurement: m/s

- platform: tcp
  name: meteobridge_wind_chill
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charset=UTF-8\n\n"
  value_template: "{{value.split (' ')[23]}}"
  unit_of_measurement: °C

- platform: tcp
  name: meteobridge_precip_rate
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charset=UTF-8\n\n"
  value_template: >-
    {{ value.split (' ')[7] | float }}
  unit_of_measurement: mm/h

- platform: tcp
  name: meteobridge_precip_total
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charaset=UTF-8\n\n"
  value_template: >-
    {{ value.split (' ')[8] | float}}
  unit_of_measurement: mm

- platform: tcp
  name: meteobridge_precip_change
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charaset=UTF-8\n\n"
  value_template: >-
    {{ value.split (' ')[9] | float }}
  unit_of_measurement: mm

- platform: tcp
  name: meteobridge_in_temp
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charaset=UTF-8\n\n"
  value_template: "{{value.split (' ')[12]}}"
  unit_of_measurement: °C

- platform: tcp
  name: meteobridge_in_humidity
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charaset=UTF-8\n\n"
  value_template: "{{value.split (' ')[13]}}"
  unit_of_measurement: '%'

- platform: tcp
  name: meteobridge_in_dewpoint
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charaset=UTF-8\n\n"
  value_template: "{{value.split (' ')[14]}}"
  unit_of_measurement: °C

- platform: tcp
  name: meteobridge_barometric_pressure
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charaset=UTF-8\n\n"
  value_template: "{{value.split (' ')[15]}}"
  unit_of_measurement: hPa

- platform: tcp
  name: meteobridge_sea_level_pressure
  host: 10.254.254.112
  port: 5556
  timeout: 6
  payload: "Content-type: text/xml; charaset=UTF-8\n\n"
  value_template: "{{value.split (' ')[16]}}"
  unit_of_measurement: hPa
        
- platform: template
  sensors:
    wind_dir_string:
      value_template: >-
        {% if states.sensor.meteobridge_wind_direction.state | float<=11 %}N
        {% elif states.sensor.meteobridge_wind_direction.state | float>348 %}N
        {% elif states.sensor.meteobridge_wind_direction.state | float<=34 | float>11 %}NNE
        {% elif states.sensor.meteobridge_wind_direction.state | float<=56 | float>34 %}NE
        {% elif states.sensor.meteobridge_wind_direction.state | float<=79 | float>56 %}ENE
        {% elif states.sensor.meteobridge_wind_direction.state | float<=101 | float>79 %}E
        {% elif states.sensor.meteobridge_wind_direction.state | float<=124 | float>101 %}ESE
        {% elif states.sensor.meteobridge_wind_direction.state | float<=146 | float>124 %}SE
        {% elif states.sensor.meteobridge_wind_direction.state | float<=169 | float>146 %}SSE
        {% elif states.sensor.meteobridge_wind_direction.state | float<=191 | float>169 %}S
        {% elif states.sensor.meteobridge_wind_direction.state | float<=214 | float>191 %}SSW
        {% elif states.sensor.meteobridge_wind_direction.state | float<=236 | float>214 %}SW
        {% elif states.sensor.meteobridge_wind_direction.state | float<=259 | float>236 %}WSW
        {% elif states.sensor.meteobridge_wind_direction.state | float<=281 | float>259 %}W
        {% elif states.sensor.meteobridge_wind_direction.state | float<=304 | float>281 %}WNW
        {% elif states.sensor.meteobridge_wind_direction.state | float<=326 | float>304 %}NW
        {% elif states.sensor.meteobridge_wind_direction.state | float<=348 | float>326 %}NNW
        {%- endif %}

- platform: influxdb
  host: a0d7b954-influxdb
  port: 8086
  username: !secret influx_user
  password: !secret influx_pass
  queries:
    - name: "Rain 24 hours total" 
      database: !secret influx_name
      unit_of_measurement: mm
      value_template: '{{ value | round(1) }}'
      field: value
      group_function: sum
      measurement: '"mm/h"'
      where: '"entity_id" = "meteobridge_precip_rate" and time > now() - 24h'
    - name: "Rain 7 days total" 
      database: !secret influx_name
      unit_of_measurement: mm
      value_template: '{{ value | round(1) }}'
      field: value
      group_function: sum
      measurement: '"mm/h"'
      where: '"entity_id" = "meteobridge_precip_rate" and time > now() - 7d'