- platform: template
  sensors:
    battery_doorbell:
      friendly_name: "Ringeklokke"
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.switch.doorbell_5_1 -%}
          {{ states.switch.doorbell_5_1.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}