- platform: rest
  resource: https://smart-me.com:443/api/Devices/2982de1e-eeda-4a1c-a8ab-a30766ce7e71
  username: !secret smart-me_user
  password: !secret smart-me_pass
  force_update: true
  name: Kamstrup RESt Counter
  unit_of_measurement: kWh
  value_template: '{{ value_json.CounterReading }}'

- platform: rest
  resource: https://smart-me.com:443/api/Devices/2982de1e-eeda-4a1c-a8ab-a30766ce7e71
  username: !secret smart-me_user
  password: !secret smart-me_pass
  force_update: true
  name: Kamstrup RESt Total Watt
  unit_of_measurement: kW
  value_template: '{{ value_json.ActivePower | round(2) }}'

- platform: rest
  resource: https://smart-me.com:443/api/Devices/2982de1e-eeda-4a1c-a8ab-a30766ce7e71
  username: !secret smart-me_user
  password: !secret smart-me_pass
  force_update: true
  name: Kamstrup RESt Spænding P1
  unit_of_measurement: V
  value_template: '{{ value_json.VoltageL1 | round(0) }}'

- platform: rest
  resource: https://smart-me.com:443/api/Devices/2982de1e-eeda-4a1c-a8ab-a30766ce7e71
  username: !secret smart-me_user
  password: !secret smart-me_pass
  force_update: true
  name: Kamstrup RESt Spænding P2
  unit_of_measurement: V
  value_template: '{{ value_json.VoltageL2 | round(0) }}'

- platform: rest
  resource: https://smart-me.com:443/api/Devices/2982de1e-eeda-4a1c-a8ab-a30766ce7e71
  username: !secret smart-me_user
  password: !secret smart-me_pass
  force_update: true
  name: Kamstrup RESt Spænding P3
  unit_of_measurement: V
  value_template: '{{ value_json.VoltageL3 | round(0) }}'

- platform: rest
  resource: https://smart-me.com:443/api/Devices/2982de1e-eeda-4a1c-a8ab-a30766ce7e71
  username: !secret smart-me_user
  password: !secret smart-me_pass
  force_update: true
  name: Kamstrup RESt Ampere P1
  unit_of_measurement: A
  value_template: '{{ value_json.CurrentL1 | round(2) }}'

- platform: rest
  resource: https://smart-me.com:443/api/Devices/2982de1e-eeda-4a1c-a8ab-a30766ce7e71
  username: !secret smart-me_user
  password: !secret smart-me_pass
  force_update: true
  name: Kamstrup RESt Ampere P2
  unit_of_measurement: A
  value_template: '{{ value_json.CurrentL2 | round(2) }}'

- platform: rest
  resource: https://smart-me.com:443/api/Devices/2982de1e-eeda-4a1c-a8ab-a30766ce7e71
  username: !secret smart-me_user
  password: !secret smart-me_pass
  force_update: true
  name: Kamstrup RESt Ampere P3
  unit_of_measurement: A
  value_template: '{{ value_json.CurrentL3 | round(2) }}'
