- platform: template
  sensors:
    battery_multisensor_repos:
      friendly_name: "Repos"
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.binary_sensor.repos_motion_42 -%}
          {{ states.binary_sensor.repos_motion_42.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
- platform: template
  sensors:
    battery_zwave_small_window:
      friendly_name: "Lille Vindue"
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.binary_sensor.lille_vindue_57 -%}
          {{ states.binary_sensor.lille_vindue_57.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
- platform: template
  sensors:
    battery_zwave_frontdoor:
      friendly_name: "Fordør"
      device_class: battery
      unit_of_measurement: '%'
      value_template: >-
        {%- if states.binary_sensor.frontdoor_59 -%}
          {{ states.binary_sensor.frontdoor_59.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
