#START COMMON
esphome:
  name: $devicename
  platform: $platform
  board: $board

wifi:
  manual_ip:
    static_ip: $ip
    gateway: $gateway
    subnet: $subnet
  domain: ".iot.trab.local"
  networks:
    - ssid: "IoT"
      bssid: "a2:2a:a8:c7:8f:d6"
      password: "Trab!IoT"
      hidden: true
    - ssid: "IoT"
      bssid: "a2:2a:a8:c4:50:ad"
      password: "Trab!IoT"
      hidden: true
    - ssid: "IoT"
      password: "Trab!IoT"
      hidden: true
  ap:
    ssid: "$fallback Fallback Hotspot"
    password: "Trab!Horsensvej50"

# Enable fallback captive portal
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow OTA feature
ota:
  password: 'Horsensvej50'

# Status sensors
sensor:
  - platform: wifi_signal
    name: "$upper_devicename WiFi Signal"
    update_interval: 10s
  - platform: uptime
    name: "$upper_devicename  Uptime"

switch:
  - platform: restart
    name: "$upper_devicename Restart"