substitutions:
  devicename: aquarea
  upper_devicename: Panasonic Aquarea
  fallback: aquarea
  platform: ESP8266
  board: esp12e
  ip: 192.168.1.206
  gateway: 192.168.1.1
  subnet: 255.255.255.0

<<: !include .common.yaml

binary_sensor:
  - platform: status
    name: "$upper_devicename Status"

