substitutions:
  devicename: carport_motion
  upper_devicename: Carport Motion
  fallback: Carport Motion
  platform: ESP8266
  board: d1_mini
  ip: 10.254.254.10
  gateway: 10.254.254.1
  subnet: 255.255.255.0

<<: !include .common.yaml

binary_sensor:
  - platform: status
    name: "$upper_devicename Status"

  - platform: gpio
    pin: D4
    name: "Motion Sensor"
    device_class: motion

sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "$upper_devicename Temperature"
    humidity:
      name: "$upper_devicename Humidity"
    update_interval: 60s
  - platform: wifi_signal
    name: "$upper_devicename WiFi Signal"
    update_interval: 10s
  - platform: uptime
    name: "$upper_devicename  Uptime"
