- platform: mqtt
  name: "Soveværelse Vindue"
  command_topic: "rullegardin/Sovevaerelse/in"
  state_topic: "rullegardin/Sovevaerelse/out"
  position_topic: "rullegardin/Sovevaerelse/out"
  set_position_topic: "rullegardin/Sovevaerelse/in"
  retain: false
  payload_open: "0"
  payload_close: "100"
  payload_stop: "(0)"
  state_open: 0
  state_closed: 100
  position_open: 0
  position_closed: 100
  optimistic: false
  value_template: '{{ value_json.set }}'